pipeline {
    agent any

    environment {
        classpath = "classes;lib/*;C:/Users/dbjin/junit-platform-console-standalone-1.13.0-RC1.jar"
    }

    stages {
        stage('Checkout') {
            steps {
                checkout scm  // 소스코드 체크아웃
            }
        }

        stage('Build') {
            steps {
                bat 'javac -encoding UTF-8 -d classes Practice/src/**/*.java'
            }
        }

        stage('Test') {
            steps {
                echo "JUnit 5 테스트 실행 중..."
                bat "java -cp ${classpath} org.junit.platform.console.ConsoleLauncher --scan-classpath | tee test_results.txt"
            }
        }
    }

    post {
        always {
            archiveArtifacts artifacts: 'test_results.txt'
        }
        failure {
            echo 'Build or test failed'
        }
        success {
            echo 'Build and test succeeded'
        }
    }
}